# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Swag Labs Sample App Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./
    env:
      BUILD_PREFIX: true
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start Sauce Connect Tunnel
      uses: saucelabs/sauce-connect-action@v2.0.0
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnelIdentifier: github-action-tunnel
        scVersion: 4.7.1
        noRemoveCollidingTunnels: true

    - name: Run E2E Tests
      run: cd test && mvn clean test
